#!/usr/bin/env python3
import hashlib,json,os,subprocess
from datetime import datetime,timezone
from pathlib import Path
R=Path(__file__).resolve().parents[2];O=R/"ai-skill"/"generated";O.mkdir(parents=True,exist_ok=True)
sha=os.environ.get("SOURCE_COMMIT") or subprocess.check_output(["git","rev-parse","HEAD"],cwd=R,text=True).strip()
c=[('native_research_entities', 'data/research_entities.json'), ('core_count_assertions', 'research/core-count-assertions.json'), ('ocbi_structure_inspection', 'research/ocbi-structure-inspection.json'), ('source_comparison_audit', 'research/source-comparison-audit.json'), ('dunand_1930_acquisition', 'research/dunand-1930-acquisition.json'), ('stele_a_count_comparison', 'research/stele-a-count-comparison.json'), ('stele_a_numbered_assertions', 'research/stele-a-numbered-assertions.json'), ('stele_a_numbering_audit', 'research/stele-a-numbering-audit.json'), ('current_status', 'analysis/current-status.json')]+[('source_reconciliation_guide','docs/SOURCE-RECONCILIATION.md'),('core_edition_locators', 'research/core-edition-locators.json'), ('edition_locator_audit', 'research/edition-locator-audit.json'), ('core_field_provenance_audit', 'research/core-field-provenance-audit.json'), ('core_publication_genealogy_audit', 'research/core-publication-genealogy-audit.json'), ('core_counting_unit_ledger', 'research/core-counting-unit-ledger.json'), ('core_primary_access_routes', 'research/core-primary-access-routes.json'), ('core_primary_access_route_audit', 'research/core-primary-access-route-audit.json'), ('dunand_1978_bibliographic_conflict_audit', 'research/dunand-1978-bibliographic-conflict-audit.json')]+[("current_status","analysis/current-status.json"),("source_inspection","research/source-inspection-2026-10-02.json"),("native_catalogue","data/catalogue.json"),("surface_inventory","data/surfaces.json"),("institutional_corpus_baseline","research/authoritative-corpus-baseline.json"),("audit","exports/audit.json"),("coverage","data/coverage.json"),("sources","data/sources.json"),("rights","docs/RIGHTS.md"),("claims","release/CLAIM-REGISTRY.csv"),("corpus_json","exports/corpus.json"),("corpus_jsonl","exports/corpus.jsonl"),("greek_subset","exports/greek-subset.json"),("eteocypriot_components","exports/eteocypriot-components.json"),("rights_matrix","DATA-LICENSE-MATRIX.md"),("rights","docs/RIGHTS.md"),("rights_and_licensing","docs/RIGHTS-AND-LICENSING.md"),("notice","NOTICE"),("third_party","THIRD-PARTY-NOTICES.md"),("core_object_reconciliation","research/core-object-reconciliation.json"),("pre_expert_maximum","research/pre-expert-maximum.json")]
a=[]
seen=set()
for role,rel in c:
 p=R/rel
 if p.is_file() and rel not in seen:
  seen.add(rel)
  b=p.read_bytes();a.append({"role":role,"path":rel,"sha256":hashlib.sha256(b).hexdigest(),"bytes":len(b)})
d={"schema_version":"0.3.1","skill_version":"0.3.1","source_commit":sha,"canonical_repository":True,"generated_at_utc":datetime.now(timezone.utc).replace(microsecond=0).isoformat(),"contract":{"corpus_is_authoritative":True,"missing_means_unknown":True,"cross_corpus_equivalence_requires_explicit_evidence":True,"preserve_uncertainty":True,"preserve_source_independence":True,"preserve_rights":True},"artifacts":a}
(O/"research-bundle-index.json").write_text(json.dumps(d,indent=2)+"\n");(O/"source-state.json").write_text(json.dumps({"schema_version":"1.0","source_commit":sha,"skill_version":"0.3.1","bundle_index":"ai-skill/generated/research-bundle-index.json"},indent=2)+"\n")
